# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='imageviewer',
    version='0.1.0',
    description='A simple image viewer made in Python.',
    python_requires='==3.*,>=3.6.0',
    author='Lucas Cavalcante da Silva',
    author_email='silva.lucasdev@gmail.com',
    license='MIT',
    packages=[
        'imageviewer', 'imageviewer.core', 'imageviewer.view',
        'imageviewer.view.widgets'
    ],
    package_dir={"": "."},
    package_data={},
    install_requires=['pyqt5==5.*,>=5.14.1'],
    extras_require={"dev": ["flake8==3.*,>=3.7.9", "yapf==0.*,>=0.29.0"]},
)
